### ISSUE TITLE
I don't know what I did and would love some help

### ISSUE THREAD

**Issue by NuttySamGreen** [mchorse/bbs-mod-wiki#1]
really cool mod, I was messing around with it but when I exported my video it resulted in this
https://www.youtube.com/watch?v=fbcCKMdShOo

it wasn't doing the moving up before the export,
I was wondering if you could help me out
let me know any info I need to give

**Comment by mchorse** [comment]
Thank you! I think it's due to older version. Are you sure you're using latest BBS mod version? 

In addition to that, please don't use this issue page for bug/crash reports or help. For this, Discord server exists: https://discord.gg/NpNvNtyrrH
