### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Gh0st1410** [mchorse/bbs-mod-wiki#2]
![{9F7A94E0-40A8-4B24-BA4E-F2C53A3528D4}](https://github.com/user-attachments/assets/9bc8b606-a96d-4b63-8465-f9834d32d81a)

**Comment by Gh0st1410** [comment]
i already installed fabric-api btw

**Comment by mchorse** [comment]
> i already installed fabric-api btw

If it shows this window, then it must mean you either didn't install it, or you didn't install it correctly. Look up how to install Fabric mods.
