### ISSUE TITLE
The Game is crashing on entry point bc of BBS

### ISSUE THREAD

**Issue by J0ril** [mchorse/bbs-mod-wiki#3]
![grafik](https://github.com/user-attachments/assets/fd020b2e-6929-42b6-940b-9784c9a8f08a)

```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bbs' at > 'mchorse.bbs_mod.BBSModClient'!
```

What am i missing?

**Comment by mchorse** [comment]
It's better to submit issues on BBS mod's Discord server: https://discord.gg/NpNvNtyrrH
